name: CI for Commerce

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./commerce

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Phiên bản Node.js Next 15 khuyên dùng
        cache: 'pnpm'
        cache-dependency-path: './commerce/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Run Linter
      run: pnpm run lint

    - name: Type Check
      run: npx tsc --noEmit

    - name: Run Build
      run: pnpm run build
